id=input("Enter your Id :")
name=input("Enter your Name :")
age=int(input("Enter your age :"))
city=input("Enter your City name :")
phone=int(input("Enter your Phone number :"))
print("Student name :"+name)
print("Student Id :"+id)
print("Student age :"+str(name))
print("Student city name :"+city)
print("Student Phone number:"+str(name))